### ISSUE TITLE
Allow more than 3 years in query

### ISSUE THREAD

**Issue by UnlimitedCookies** [openpotato/openholidaysapi.website#5]
I noticed that `curl -X GET "https://openholidaysapi.org/PublicHolidays?countryIsoCode=DE&subdivisionCode=DE-NW&languageIsoCode=DE&validFrom=2024-01-01&validTo=2026-12-31" -H "accept: text/calendar"` returns a response, while `curl -X GET "https://openholidaysapi.org/PublicHolidays?countryIsoCode=DE&subdivisionCode=DE-NW&languageIsoCode=DE&validFrom=2024-01-01&validTo=2027-12-31" -H "accept: text/calendar"` doesn't respond with anything. There should be at least some error code returned, but better would be to simply increase the limit.

**Comment by fstueber** [comment]
OpenHolidays API does respond with an error code (500) in your second example. You have to include the `-I` parameter for the curl call. Try:

```
curl -X GET "https://openholidaysapi.org/PublicHolidays?countryIsoCode=DE&subdivisionCode=DE-NW&languageIsoCode=DE&validFrom=2024-01-01&validTo=2027-12-31" -H "accept: text/calendar" -I
```

Error codes are too generic at the moment, this I will change in future versions. About the date range limit. It's 3 years by design at the moment. Could you tell me more about your use case?

**Comment by UnlimitedCookies** [comment]
My use case btw is to import all holidays in my personal calendar. Therefore I don't want to have to change the url every time (and also having all dates is also useful).
